import { createElement } from '@lwc/engine-dom';
import DRC_NBC_CloneQuote from 'c/dRC_NBC_CloneQuote';

describe('c-d-r-c-n-b-c-clone-quote', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-d-r-c-n-b-c-clone-quote', {
            is: DRC_NBC_CloneQuote
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});